# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('catid', models.TextField()),
                ('price', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.TextField()),
                ('catname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.TextField()),
                ('isbn', models.TextField()),
                ('item_price', models.TextField()),
                ('quantity', models.TextField()),
                ('primary_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('customerid', models.TextField()),
                ('amount', models.IntegerField()),
                ('date', models.TextField()),
                ('order_status', models.TextField()),
                ('ship_name', models.TextField()),
                ('ship_address', models.IntegerField()),
                ('ship_city', models.TextField()),
                ('ship_state', models.TextField()),
                ('ship_zip', models.IntegerField()),
                ('ship_country', models.TextField()),
            ],
        ),
    ]
